config/routes.rb
MonthByMonth::Application.routes.draw do

  get "pages/home"

  resources :months
  resources :features

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :month
  validates_prescence_of :desc
end

app/models/month.rb
class Month < ActiveRecord::Base
  has_many :features
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  # GET /features
  # GET /features.json
  def index
    @features = Feature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @feature = Feature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = Feature.find(params[:id])
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  # GET /months
  # GET /months.json
  def index
    @months = Month.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @months }
    end
  end

  # GET /months/1
  # GET /months/1.json
  def show
    @month = Month.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @month }
    end
  end

  # GET /months/new
  # GET /months/new.json
  def new
    @month = Month.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @month }
    end
  end

  # GET /months/1/edit
  def edit
    @month = Month.find(params[:id])
  end

  # POST /months
  # POST /months.json
  def create
    @month = Month.new(params[:month])

    respond_to do |format|
      if @month.save
        format.html { redirect_to @month, notice: 'Month was successfully created.' }
        format.json { render json: @month, status: :created, location: @month }
      else
        format.html { render action: "new" }
        format.json { render json: @month.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /months/1
  # PUT /months/1.json
  def update
    @month = Month.find(params[:id])

    respond_to do |format|
      if @month.update_attributes(params[:month])
        format.html { redirect_to @month, notice: 'Month was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @month.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /months/1
  # DELETE /months/1.json
  def destroy
    @month = Month.find(params[:id])
    @month.destroy

    respond_to do |format|
      format.html { redirect_to months_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
   # Return a title on a per-page basis.
  def title
    base_title = "Bendafe Month By Month"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/features/_form.html.erb
<%= form_for(@feature) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
<<<<<<< HEAD
=======
    <%= f.label :plant %><br />
    <%= f.text_area :plant %>
  </div>
  <div class="field">
>>>>>>> working
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<h1>Listing features</h1>

<table>
  <tr>
<<<<<<< HEAD
=======
    <th>Plant</th>
>>>>>>> working
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @features.each do |feature| %>
  <tr>
<<<<<<< HEAD
=======
    <td><%= feature.plant %></td>
>>>>>>> working
    <td><%= feature.desc %></td>
    <td><%= link_to 'Show', feature %></td>
    <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
    <td><%= link_to 'Destroy', feature, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feature', new_feature_path %>

app/views/features/new.html.erb
<h1>New feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<<<<<<< HEAD
=======
  <b>Plant:</b>
  <%= @feature.plant %>
</p>

<p>
>>>>>>> working
  <b>Desc:</b>
  <%= @feature.desc %>
</p>


<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>

app/views/home/index.html.erb
<div id="masthead"> 
  <h1 id="siteName">Bendaf&eacute;  month by month </h1> 
</div> 
<%= link_to "Current month", months_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/months/_form.html.erb
<%= form_for(@month) do |f| %>
  <% if @month.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@month.errors.count, "error") %> prohibited this month from being saved:</h2>

      <ul>
      <% @month.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/months/edit.html.erb
<h1>Editing month</h1>

<%= render 'form' %>

<%= link_to 'Show', @month %> |
<%= link_to 'Back', months_path %>

app/views/months/index.html.erb
<h1>Listing months</h1>

<table>
  <tr>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @months.each do |month| %>
  <tr>
    <td><%= month.desc %></td>
    <td><%= link_to 'Show', month %></td>
    <td><%= link_to 'Edit', edit_month_path(month) %></td>
    <td><%= link_to 'Destroy', month, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Month', new_month_path %>

app/views/months/new.html.erb
<h1>New month</h1>

<%= render 'form' %>

<%= link_to 'Back', months_path %>

app/views/months/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @month.desc %>
</p>


<%= link_to 'Edit', edit_month_path(@month) %> |
<%= link_to 'Back', months_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>